// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCrypto.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Coins", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/bitcoin.png",
                            Valor = 21295.799999999999
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Ethereum",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/ethereum.png",
                            Valor = 1347.4400000000001
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Solana",
                            ImageUrl = "https://cryptologos.cc/logos/solana-sol-logo.png",
                            Valor = 39.807000000000002
                        },
                        new
                        {
                            MonedaId = 4,
                            Descripcion = "Binance",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/binance-usd.png",
                            Valor = 1.0002
                        },
                        new
                        {
                            MonedaId = 5,
                            Descripcion = "Shiba Inu",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/shiba-inu.png",
                            Valor = 1.099E-05
                        },
                        new
                        {
                            MonedaId = 6,
                            Descripcion = "Cardano",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/cardano.png",
                            Valor = 0.45250000000000001
                        },
                        new
                        {
                            MonedaId = 7,
                            Descripcion = "Uniswap",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/uniswap.png",
                            Valor = 7.2901999999999996
                        },
                        new
                        {
                            MonedaId = 8,
                            Descripcion = "Chainlink",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/chainlink.png",
                            Valor = 6.4900000000000002
                        },
                        new
                        {
                            MonedaId = 9,
                            Descripcion = "Aave",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/aave.png",
                            Valor = 91.099999999999994
                        },
                        new
                        {
                            MonedaId = 10,
                            Descripcion = "Bitcoin Cash",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/bitcoin-cash.png",
                            Valor = 109.09999999999999
                        },
                        new
                        {
                            MonedaId = 11,
                            Descripcion = "Flow",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/flow.png",
                            Valor = 1.589
                        },
                        new
                        {
                            MonedaId = 12,
                            Descripcion = "Decentraland",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/decentraland.png",
                            Valor = 0.85980000000000001
                        },
                        new
                        {
                            MonedaId = 13,
                            Descripcion = "Internet Computer",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/internet-computer.png",
                            Valor = 7.0800000000000001
                        },
                        new
                        {
                            MonedaId = 14,
                            Descripcion = "Pax Dollar",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/paxos-standard.png",
                            Valor = 1.0003
                        },
                        new
                        {
                            MonedaId = 15,
                            Descripcion = "Zcash",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/zcash.png",
                            Valor = 63.170000000000002
                        },
                        new
                        {
                            MonedaId = 16,
                            Descripcion = "The Graph",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/the-graph.png",
                            Valor = 0.10077
                        },
                        new
                        {
                            MonedaId = 17,
                            Descripcion = "Chiliz",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/chiliz.png",
                            Valor = 0.11070000000000001
                        },
                        new
                        {
                            MonedaId = 18,
                            Descripcion = "Neo",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/neo.png",
                            Valor = 9.2603000000000009
                        },
                        new
                        {
                            MonedaId = 19,
                            Descripcion = "Curve DAO Token",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/curve-dao-token.png",
                            Valor = 1.1812
                        },
                        new
                        {
                            MonedaId = 20,
                            Descripcion = "Mina",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/mina.png",
                            Valor = 0.68500000000000005
                        },
                        new
                        {
                            MonedaId = 21,
                            Descripcion = "PancakeSwap",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/pancakeswap.png",
                            Valor = 3.2509999999999999
                        },
                        new
                        {
                            MonedaId = 22,
                            Descripcion = "NEM",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/nem.png",
                            Valor = 0.042029999999999998
                        },
                        new
                        {
                            MonedaId = 23,
                            Descripcion = "Kava.io",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/kava.png",
                            Valor = 1.752
                        },
                        new
                        {
                            MonedaId = 24,
                            Descripcion = "Basic Attention Token",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/basic-attention-token.png",
                            Valor = 0.39557999999999999
                        },
                        new
                        {
                            MonedaId = 25,
                            Descripcion = "Maker",
                            ImageUrl = "https://i-invdn-com.investing.com/ico_flags/80x80/v32/maker.png",
                            Valor = 960.58000000000004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
